### ISSUE TITLE
jpeg-xl version in .rb files doesn't match 0.70 in Cellar?

### ISSUE THREAD

**Issue by satmandu** [spaceshiptrooper/homebrew#1]
Did you want some version of https://raw.githubusercontent.com/Homebrew/homebrew-core/b1390deabb33912548b21b69839575a2cd4e6cbe/Formula/jpeg-xl.rb?

(I'm trying to build mpv on 10.13, so thanks for putting this together.)

**Comment by satmandu** [comment]
Even so I'm getting this issue with the 0.7.0 build...
`HOMEBREW_NO_AUTO_UPDATE=1 brew install jpeg-xl`:

```
[ 59%] Building CXX object lib/CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o
cd /tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DHWY_DISABLED_TARGETS="(HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128|HWY_RVV)" -DJPEGXL_MAJOR_VERSION=0 -DJPEGXL_MINOR_VERSION=7 -DJPEGXL_PATCH_VERSION=0 -DJXL_INTERNAL_LIBRARY_BUILD -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0 -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/lib/include -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/third_party/skcms -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/build/lib/include -fno-rtti -funwind-tables -Xclang -mrelax-all -Xclang -mconstructor-aliases -fno-omit-frame-pointer -O3 -DNDEBUG -O2 -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -Wall -fmerge-all-constants -fno-builtin-fwrite -fno-builtin-fread -Wextra -Wc++11-compat -Warray-bounds -Wformat-security -Wimplicit-fallthrough -Wno-register -Wno-unused-function -Wno-unused-parameter -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -Wdeprecated-increment-bool -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wgnu-redeclared-enum -Winfinite-recursion -Wliteral-conversion -Wno-c++98-compat -Wno-unused-command-line-argument -Wprivate-header -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety-analysis -Wundefined-func-template -Wunreachable-code -Wunused-comparison -fsized-deallocation -fno-exceptions -fmath-errno -fnew-alignment=8 -fno-cxx-exceptions -fno-slp-vectorize -fno-vectorize -disable-free -disable-llvm-verifier -DJPEGXL_ENABLE_SKCMS=1 -DJPEGXL_BUNDLE_SKCMS=1 -MD -MT lib/CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o -MF CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o.d -o CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o -c /tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/lib/jxl/progressive_split.cc
[ 59%] Built target jxl_enc-obj
make: *** [all] Error 2
```

Which matches the error with the 0.8.1 build...

**Comment by spaceshiptrooper** [comment]
> Even so I'm getting this issue with the 0.7.0 build... `HOMEBREW_NO_AUTO_UPDATE=1 brew install jpeg-xl`:
> 
> ```
> [ 59%] Building CXX object lib/CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o
> cd /tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/build/lib && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DHWY_DISABLED_TARGETS="(HWY_SVE|HWY_SVE2|HWY_SVE_256|HWY_SVE2_128|HWY_RVV)" -DJPEGXL_MAJOR_VERSION=0 -DJPEGXL_MINOR_VERSION=7 -DJPEGXL_PATCH_VERSION=0 -DJXL_INTERNAL_LIBRARY_BUILD -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0 -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/lib/include -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/third_party/skcms -I/tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/build/lib/include -fno-rtti -funwind-tables -Xclang -mrelax-all -Xclang -mconstructor-aliases -fno-omit-frame-pointer -O3 -DNDEBUG -O2 -std=c++11 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-builtin-macro-redefined -Wall -fmerge-all-constants -fno-builtin-fwrite -fno-builtin-fread -Wextra -Wc++11-compat -Warray-bounds -Wformat-security -Wimplicit-fallthrough -Wno-register -Wno-unused-function -Wno-unused-parameter -Wnon-virtual-dtor -Woverloaded-virtual -Wvla -Wdeprecated-increment-bool -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wgnu-redeclared-enum -Winfinite-recursion -Wliteral-conversion -Wno-c++98-compat -Wno-unused-command-line-argument -Wprivate-header -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety-analysis -Wundefined-func-template -Wunreachable-code -Wunused-comparison -fsized-deallocation -fno-exceptions -fmath-errno -fnew-alignment=8 -fno-cxx-exceptions -fno-slp-vectorize -fno-vectorize -disable-free -disable-llvm-verifier -DJPEGXL_ENABLE_SKCMS=1 -DJPEGXL_BUNDLE_SKCMS=1 -MD -MT lib/CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o -MF CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o.d -o CMakeFiles/jxl_enc-obj.dir/jxl/progressive_split.cc.o -c /tmp/jpeg-xl-20230426-22378-xt7cs1/libjxl-0.7.0/lib/jxl/progressive_split.cc
> [ 59%] Built target jxl_enc-obj
> make: *** [all] Error 2
> ```
> 
> Which matches the error with the 0.8.1 build...

Hey, sorry for not responding back earlier. I actually found out that you can "spoof" the version number to the latest version. So whenever you do an upgrade, it'll try to download the latest version of that keg. Copy that formula version and stop the terminal from downloading the latest version. After that, change the current version you have installed to the latest version by just renaming the folder name to that latest version you copied. It'll trick Homebrew into thinking you already have the "latest" version which you really don't.

I have no expertise in Ruby so I wouldn't know what's really wrong with the keg files. I just know that I can do all of these workarounds "just" to get PHP up and going because that's all that really matters to me. I don't care if I have outdated Homebrew formulas. At least the PHP installation I have is up-to-date. Once you have the formula version "spoof" concept working, upgrading PHP in itself is very easy since it's just the normal `brew upgrade` that will take care of PHP's version.

So PHP in itself isn't the issue nor are there any broken versions for PHP as far as I know using macOS Mojave. I'm currently running PHP 8.2.7 and it's working on one of my Mojave installation. I'm currently working on getting PHP 8.2.8 (latest version as of 7/7/2023) installed right now. The main issue is that there a lot of dependencies that PHP uses that are apparently broken for older versions of macOS, but not PHP itself.

----

EDIT: Here's my PHP installation running on PHP 8.2.8 as of today (7/17/2023).
![Screen Shot 2023-07-17 at 9 37 37 AM](https://github.com/spaceshiptrooper/homebrew/assets/22463623/39c05c95-4b13-42c9-ac69-f43f75156ffc)

**Comment by satmandu** [comment]
Thanks! I gave up on getting a modern version of mpv with deps built on 10.13. :)
Good luck with PHP! I've helped with getting builds working in chromebrew, and it's a royal pain....
